name: PIP Business Rules
apiVersion: v3
home: https://github.com/hmcts/pip-business-rules
version: 0.0.4
description: Publishing & Information Business Rules
maintainers:
  - name: HMCTS PIP Team
dependencies:
  - name: java
    version: 3.5.1
    repository: '@hmctspublic'
